### PR TITLE
AP-Photogram Industrial pt1: Devise accounts and photos scaffold

### PR DESCRIPTION
**Pull request by APatel-AI**
- Integrated devise gem for user authentication
- generated users with devise
- created photo scaffold

### CODE REVIEW

**Comment by thierrychau** [comment]
Hi Arpan, can you find a peer to review this before I do so? Thanks

**Review by dylansarikas — APPROVED** [review]
Looks good Arpan!!

**Comment by thierrychau** [comment]
Can you add part 2 to this PR also? Thanks

**Review by thierrychau — APPROVED** [review]
Good to merge!

**Pull request merged**
